version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test_portfolio_development
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 13306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      DB_HOST: db
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_PORT: 3306
    ports:
      - 3030:3000
    depends_on:
      - db
volumes:
  db-data:
  bundle-data: