version: 2
jobs:
  build:
    working_directory: ~/my_portfolio
    environment:
      RAILS_ENV: test
      NODE_ENV: test
      NEW_PORTFOLIO_DATABASE_USER: root
      NEW_PORTFOLIO_DATABASE_PASSWORD: ''
      NEW_PORTFOLIO_DATABASE_HOST: 127.0.0.1
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/ruby:2.6.3-node-browsers
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      # Download and cache dependencies
      ## RubyGems
      - restore_cache:
          key: gem-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install gem dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: gem-dependencies-{{ checksum "Gemfile.lock" }}

      ## Node Packages
#      - restore_cache:
#          key: npm-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install npm dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Setup Database
          command: |
            bundle exec rails db:create db:schema:load
      - run:
          name: Test > RSpec
          command: |
            bundle exec rspec --format progress \
                                        --profile \
                                        -- $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split)
      - run:
          name: Test > Jest
          command: |
            yarn run test --maxWorkers=2
      - run:
          name: Lint > Rubocop
          command: |
            bundle exec rubocop
      - run:
          name: Lint > TSLint
          command: |
            yarn run lint
      # Reports to Codecov
      - store_artifacts:
          path: coverage